### ISSUE TITLE
Out-of-GPU memory when computing FactorVAE metric

### ISSUE THREAD

**Issue by mseitzer** [AIcrowd/neurips2019_disentanglement_challenge_starter_kit#11]
Hi,

I am running into problems with my approach as computing the FactorVAE metric requires huge amount of GPU memory as it is currently implemented (see https://github.com/google-research/disentanglement_lib/issues/11). Basically, the model is run on a batch size of 10000, which does not fit in the 11GB GPU memory of the K80.

Is there any workaround around this problem?

Thanks!

**Comment by obachem** [comment]
Thanks for bringing this to our attention. We have uploaded version 1.1 which should fix this issue.
