### ISSUE TITLE
Invalid link in README.md

### ISSUE THREAD

**Issue by Rauf-Kurbanov** [AIcrowd/neurips2019_disentanglement_challenge_starter_kit#5]
In the following README section:

> # What should my code structure be like ?
> 
> Please follow the structure documented in the included [run.py](https://github.com/AIcrowd/neurips2019_disentanglement_challenge_starter_kit/blob/master/run.py) to adapt
> your already existing code to the required structure for this round.

https://github.com/AIcrowd/neurips2019_disentanglement_challenge_starter_kit/blob/master/run.py link is invalid: there is no `run.py` in `master` branch

**Comment by nasimrahaman** [comment]
If I'm not mistaken, it should actually be [run.sh](https://github.com/AIcrowd/neurips2019_disentanglement_challenge_starter_kit/blob/master/run.sh), which just calls [train.py](https://github.com/AIcrowd/neurips2019_disentanglement_challenge_starter_kit/blob/master/train.py). @spMohanty could you please confirm?

**Comment by MJ10** [comment]
> Please follow the structure documented in the included run.py to adapt
your already existing code to the required structure for this round.
So this is probably referring to the training code, which is located in `train.py` so I think it should be `train.py`

**Comment by spMohanty** [comment]
@Rauf-Kurbanov : You are right. It should be `train.py`, fixing it right away.
